## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Team List and Credits:
- Ricardo Aguiar Bomeny: 
- Thiago Donato: 
- Darren Rauvola: Analysis, Conceptualization, Experimental investigation, Writing - original draft 
- Kiame McCartha: Hypothesis
- Dmitri Singer:

# Research Question

Out of these three categories of features: temporal features (hour, day of week, holidays), spatial features (pickup zone), and weather conditions (temperature, precipitation, snowfall) which one feature or combination of features is most important in forecasting taxi demand (number of rides per time interval - daily or hourly) in New York City?

## Background and Prior Work


Taxi services are a key part of NYC's urban lifestyle. The iconic yellow cabs completed over 200 million trips annually before the pandemic <a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1). Surprisingly, we found out that the NYC Taxi and Limousine Commission (TLC) documents their trips extensively since 2009. This makes it into one of the largest and most thorough urban mobility datasets in the world. The data includes features like pickup and dropoff locations, timestamps, fare information, payment type, and passenger counts for every metered taxi ride. We were blown away when we saw this! There were almost infinite questions we could ask or investigate. We thought of predicting taxi demand because it is a key component for companies that want to optimize fleet allocation, drivers who want to be in high-demand areas, and city planners so they can manage transportation policy based on demand.<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2)

Previous research has shown that taxi demand follows predictable spatiotemporal patterns. Moreira-Matias et al. (2013) investigated how time-series forecasting methods work for capturing hourly and daily demand cycles. They found that temporal features such as hour of day and day of week were one of the strongest predictors of taxi pickups <a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3).

Besides this, inspired by recent extreme weather in NYC, we thought about investigating whether weather conditions impact taxi ridership patterns. Singhal et al. (2014) did a comprehensive analysis of weather effects on NYC rides and found that precipitation has a statistically significant positive effect on taxi demand (as rain increases, more people choose taxis over walking or waiting for buses) <a name="cite_ref-4"></a>[<sup>4</sup>](#cite_note-4). The same was true for extreme heat.

Our project builds on this prior work by developing an integrated prediction model that combines temporal features (hour, day of week, month), spatial features (pickup zone), and weather conditions (temperature, precipitation) to forecast taxi demand + fare distribution. While previous studies have looked at these features separately, we'll try to quantify their relative importance using feature importance analysis and compare the predictive performance of multiple machine learning models including Linear Regression, Random Forest, and maybe even neural networks. 

Using recent TLC trip data and NOAA weather observations from Central Park, we will evaluate whether the patterns identified in earlier research hold in contemporary data and identify which factors most strongly drive taxi demand in New York City.

Citations:
1. <a name="cite_note-1"></a> [^](#cite_ref-1) NYC Taxi and Limousine Commission. (2024). TLC Trip Record Data. https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

2. <a name="cite_note-2"></a> [^](#cite_ref-2) Correa, D. & Moyano, C. (2023). Analysis and prediction of New York City taxi and Uber demands. Journal of Applied Research and Technology, 21(5), 886-898.

3. <a name="cite_note-3"></a> [^](#cite_ref-3) Moreira-Matias, L., Gama, J., Ferreira, M., Mendes-Moreira, J., & Damas, L. (2013). Predicting taxi-passenger demand using streaming data. IEEE Transactions on Intelligent Transportation Systems, 14(3), 1393-1402.

4. <a name="cite_note-4"></a> [^](#cite_ref-4) Singhal, A., Kamga, C., & Yazici, A. (2014). Impact of weather on urban transit ridership. Transportation Research Part A: Policy and Practice, 69, 379-391.

# Hypothesis

- Temporal feature relevance: We believe that temporal features like hour of day and holidays will be most correlated with taxi demand because of things like "rush hour" and from our personal experience trying to get a taxi/uber during valentines at dinner time for example is much harder than on non-holiday dates. We don't think day of the week plays a significant role as much as these other temporal features because in a busy city like NY, the variability of the things people do in a given day is too high to be able to claim that there is a special day of the week where demand is higher. We think demand per day will average out to be about the same.
- Spacial feature relevance: We believe that some burrows will have much higher demand than others simply because of the functional role of that burrow (eg. living spaces vs work spaces vs social spaces), with Manhattan (for its social/work areas) being the most busy.
- Weather feature relevance: We think extreme temperatures (<50F and >90F), high precipitations (>10mm/h), and snowfall (any snowfall > 0in) will increase taxi demand. We think these will play a significant role because people generally don't want to walk in these conditions (as mentioned in [4] above).

## Data

### Data overview

We use three datasets that together allow us to model NYC taxi demand as a function of time, location, and weather:

- **Dataset 1 — NYC Yellow Taxi Trip Records (Dec 2024–Feb 2025)**
  - Source: [NYC Taxi & Limousine Commission (TLC)](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
  - Observations: ~11 million trips (3 monthly parquet files)
  - Variables: 20 columns including pickup/dropoff timestamps, location zone IDs, passenger count, trip distance, fare amount, and surcharges
  - Key variables: `tpep_pickup_datetime`, `PULocationID`, `passenger_count`, `trip_distance`, `fare_amount`, `total_amount`
  - Shortcomings: ~25% of rows have null `passenger_count`. Some trips have dates outside the expected month. No rider demographics.

- **Dataset 2 — NOAA Daily Weather Summaries (Dec 2024–Feb 2025)**
  - Source: [NOAA Climate Data Online](https://www.ncdc.noaa.gov/cdo-web/) — Station USW00094728 (Central Park, NYC)
  - Observations: 90 daily records
  - Variables: 6 columns — `date`, `temp_max_f`, `temp_min_f`, `precipitation_in`, `snowfall_in`, `snow_on_ground_in`
  - Parsed from official NOAA PDF reports.
  - Shortcomings: Single weather station for all of NYC; actual weather may be different in other boroughs.

- **Dataset 3 — NYC Taxi Zone Lookup**
  - Source: [NYC TLC](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
  - Observations: 265 zones
  - Variables: `LocationID`, `Borough`, `Zone`, `service_zone`
  - Maps numeric zone IDs in the trip data to human-readable borough and zone names.

**Combining the datasets:** Taxi trips are joined to the zone lookup on `PULocationID = LocationID` to add borough/zone names. A `date` column extracted from pickup timestamps joins trips with daily weather. The final merged dataset has one row per trip with added borough/zone names and that day's weather conditions.

In [4]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [5]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://drive.google.com/uc?id=1uqW6HLQWbky5cZA_OmJGp1VRdFCcWrSY', 'filename': 'yellow_tripdata_2024-12.parquet' },
    { 'url': 'https://drive.google.com/uc?id=1TdzWDei4EQNvA192MRh9ViAAGd9Om_hp', 'filename': 'yellow_tripdata_2025-01.parquet' },
    { 'url': 'https://drive.google.com/uc?id=1Csr-9K8WW4kjpdo3ile8dcnk4NsIJ9ic', 'filename': 'yellow_tripdata_2025-02.parquet' },
    { 'url': 'https://drive.google.com/uc?id=1n2nCwsrrD-z_K12KgGtPBmtzQQ4uvTUS', 'filename': 'weather.csv' },
    { 'url': 'https://drive.google.com/uc?id=1EBxlK--zYYWDTyqdPKF903ShGRvu5bjf', 'filename': 'taxi_zone_lookup.csv' },
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/drauvola/.local/lib/python3.11/site-packages (2.32.5)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (4.66.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

Overall Download Progress:   0%|          | 0/5 [00:00<?, ?it/s]
Downloading yellow_tripdata_2024-12.parquet:   0%|          | 0.00/61.5M [00:00<?, ?B/s]
Downloading yellow_tripdata_2024-12.parquet:   1%|          | 314k/61.5M [00:00<00:19, 3.14MB/s]
Downloading yellow_tripdata_2024-12.parquet:   3%|▎         | 1.83M/61.5M [00:00<00:05, 10.1MB/s]
Downloading yellow_tripdata_2024-12.parquet:  10%|█         | 6.38M/61.5M [00:00<00:02, 26.2MB/s]
Downloading yellow_tripdata_2024-12.parquet:  21%|██        | 12.7M/61.5M [00:00<00:01, 40.7MB/s]
Downloading yellow_tripdata_2024-12.parquet:  27%|██▋       | 16.8M/61.5M [00:00<00:01, 29.8MB/s]
Downloading yellow_tripdata_2024-12.parquet:  38%|███▊      | 23.4M/61.5M [00:00<00:00, 39.7MB/s]
Downloading yellow_tripdata_2024-12.parquet:  48%|████▊     | 29.3M/61.5M [00:00<00:00, 45.0MB/s]
Downloading yellow_tripdata_2024-12.parquet:  56%|█████▌    | 34.2M/61.5M [00:00<00:00, 44.8MB/s]
Downloading yellow_tripdata_2024-12.parquet:  65%|██████▌   | 40.2M/61.5M [00:01<00:00, 49.2MB/s]
Downloading yellow_tripdata_2024-12.parquet:  74%|███████▎  | 45.3M/61.5M [00:01<00:00, 34.3MB/s]
Downloading yellow_tripdata_2024-12.parquet:  83%|████████▎ | 51.1M/61.5M [00:01<00:00, 39.4MB/s]
Downloading yellow_tripdata_2024-12.parquet:  92%|█████████▏| 56.8M/61.5M [00:01<00:00, 43.7MB/s]
Overall Download Progress:  20%|██        | 1/5 [00:04<00:16,  4.07s/it]

Successfully downloaded: yellow_tripdata_2024-12.parquet

Downloading yellow_tripdata_2025-01.parquet:   0%|          | 0.00/59.2M [00:00<?, ?B/s]
Downloading yellow_tripdata_2025-01.parquet:   1%|          | 356k/59.2M [00:00<00:16, 3.56MB/s]
Downloading yellow_tripdata_2025-01.parquet:   3%|▎         | 1.87M/59.2M [00:00<00:05, 10.4MB/s]
Downloading yellow_tripdata_2025-01.parquet:  12%|█▏        | 6.96M/59.2M [00:00<00:01, 28.9MB/s]
Downloading yellow_tripdata_2025-01.parquet:  22%|██▏       | 13.0M/59.2M [00:00<00:01, 41.4MB/s]
Downloading yellow_tripdata_2025-01.parquet:  29%|██▉       | 17.1M/59.2M [00:00<00:01, 28.4MB/s]
Downloading yellow_tripdata_2025-01.parquet:  38%|███▊      | 22.4M/59.2M [00:00<00:01, 34.7MB/s]
Downloading yellow_tripdata_2025-01.parquet:  48%|████▊     | 28.3M/59.2M [00:00<00:00, 41.4MB/s]
Downloading yellow_tripdata_2025-01.parquet:  56%|█████▌    | 32.9M/59.2M [00:00<00:00, 40.6MB/s]
Downloading yellow_tripdata_2025-01.parquet:  63%|██████▎   | 37.3M/59.2M [00:01<00:00, 41.3MB/s]
Downloading yellow_tripdata_2025-01.parquet:  70%|███████   | 41.7M/59.2M [00:01<00:00, 37.9MB/s]
Downloading yellow_tripdata_2025-01.parquet:  78%|███████▊  | 46.0M/59.2M [00:01<00:00, 39.4MB/s]
Downloading yellow_tripdata_2025-01.parquet:  88%|████████▊ | 52.2M/59.2M [00:01<00:00, 45.5MB/s]
Downloading yellow_tripdata_2025-01.parquet:  96%|█████████▌| 56.9M/59.2M [00:01<00:00, 44.1MB/s]
Overall Download Progress:  40%|████      | 2/5 [00:09<00:14,  4.67s/it]

Successfully downloaded: yellow_tripdata_2025-01.parquet

Downloading yellow_tripdata_2025-02.parquet:   0%|          | 0.00/60.3M [00:00<?, ?B/s]
Downloading yellow_tripdata_2025-02.parquet:   1%|          | 323k/60.3M [00:00<00:18, 3.20MB/s]
Downloading yellow_tripdata_2025-02.parquet:   3%|▎         | 1.77M/60.3M [00:00<00:05, 9.83MB/s]
Downloading yellow_tripdata_2025-02.parquet:  12%|█▏        | 7.00M/60.3M [00:00<00:01, 29.1MB/s]
Downloading yellow_tripdata_2025-02.parquet:  21%|██        | 12.6M/60.3M [00:00<00:01, 32.4MB/s]
Downloading yellow_tripdata_2025-02.parquet:  31%|███       | 18.4M/60.3M [00:00<00:01, 40.7MB/s]
Downloading yellow_tripdata_2025-02.parquet:  37%|███▋      | 22.6M/60.3M [00:00<00:01, 31.9MB/s]
Downloading yellow_tripdata_2025-02.parquet:  49%|████▊     | 29.4M/60.3M [00:00<00:01, 30.9MB/s]
Downloading yellow_tripdata_2025-02.parquet:  56%|█████▌    | 33.6M/60.3M [00:01<00:00, 30.6MB/s]
Downloading yellow_tripdata_2025-02.parquet:  63%|██████▎   | 37.7M/60.3M [00:01<00:00, 25.1MB/s]
Downloading yellow_tripdata_2025-02.parquet:  73%|███████▎  | 44.2M/60.3M [00:01<00:00, 32.8MB/s]
Downloading yellow_tripdata_2025-02.parquet:  80%|███████▉  | 48.1M/60.3M [00:01<00:00, 31.3MB/s]
Downloading yellow_tripdata_2025-02.parquet:  90%|█████████ | 54.6M/60.3M [00:01<00:00, 38.6MB/s]
Downloading yellow_tripdata_2025-02.parquet:  98%|█████████▊| 59.0M/60.3M [00:01<00:00, 38.5MB/s]
Overall Download Progress:  60%|██████    | 3/5 [00:14<00:09,  4.76s/it]

Successfully downloaded: yellow_tripdata_2025-02.parquet

Downloading weather.csv:   0%|          | 0.00/3.11k [00:00<?, ?B/s]
Overall Download Progress:  80%|████████  | 4/5 [00:15<00:03,  3.32s/it]

Successfully downloaded: weather.csv

Downloading taxi_zone_lookup.csv:   0%|          | 0.00/12.3k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 5/5 [00:18<00:00,  3.72s/it]

Successfully downloaded: taxi_zone_lookup.csv

### Dataset 1: NYC Yellow Taxi Trip Records (Dec 2024–Feb 2025)

The NYC Taxi and Limousine Commission publishes monthly trip-level records for all yellow taxi rides. Each row is a single metered trip:

- **tpep_pickup_datetime / tpep_dropoff_datetime** — Timestamps recorded by the taximeter, defining when and how long each trip lasted.
- **PULocationID / DOLocationID** — Integer codes (1–265) identifying the taxi zone for pickup and dropoff. These map to the zone lookup table.
- **passenger_count** — Self-reported by the driver; ranges 0–9 but most trips carry 1–2. About 25% of records have this field null (all from VendorID 1), meaning it is missing systematically by vendor, not at random. Could be a red flag for VendorID 1, and maybe best to remove these rows.
- **trip_distance** — Distance in miles from the taximeter. Zero values indicate cancelled trips or meter errors so we need to remove those
- **fare_amount** — Base fare in USD. Negative values occasionally appear from adjustments.
- **total_amount** — Fare + surcharges + tips + tolls. What the rider actually paid.

**Concerns:** Some trips have dates outside the nominal month (e.g., Nov 30 in the December file). Trips with 0 passengers, 0 distance, or negative fares are meter errors or cancellations. LocationIDs 264 and 265 correspond to "Unknown" zones. All of these are filtered during cleaning.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load raw taxi trip files
taxi_files = [
    'data/00-raw/yellow_tripdata_2024-12.parquet',
    'data/00-raw/yellow_tripdata_2025-01.parquet',
    'data/00-raw/yellow_tripdata_2025-02.parquet',
]
# put all months together in one df
taxi_raw = pd.concat([pd.read_parquet(f) for f in taxi_files], ignore_index=True)

print(f"Raw shape: {taxi_raw.shape}")
print(f"\nColumn dtypes:")
print(taxi_raw.dtypes)
print(f"\nNull counts:")
print(taxi_raw.isnull().sum())
print(f"\nDate range: {taxi_raw['tpep_pickup_datetime'].min()} to {taxi_raw['tpep_pickup_datetime'].max()}")

Raw shape: (10721140, 20)

Column dtypes:
VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

Null counts:
VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          1673377
trip_distance                  0
RatecodeID               1673377
store_and_fwd_flag       1673377
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     1673377
Airport_fee              1673377
cbd_congestion_fee       3668371
dtype: int64

Date range: 2008-12-31 23:03:59 to 2025-03-23 20:42:06

In [7]:
# check if any columns are null
null_cols = taxi_raw.columns[taxi_raw.isnull().any()]
print("Columns with nulls:", list(null_cols))

# are nulls random or are they all from the same vendor?
print("\nNull passenger_count by VendorID:")
print(taxi_raw.groupby('VendorID')['passenger_count'].apply(lambda x: x.isnull().sum()))
print("\nThis confirms nulls come entirely from VendorID 1 (not missing at random).")

Columns with nulls: ['passenger_count', 'RatecodeID', 'store_and_fwd_flag', 'congestion_surcharge', 'Airport_fee', 'cbd_congestion_fee']

Null passenger_count by VendorID:
VendorID
1     267538
2    1404606
6       1233
7          0
Name: passenger_count, dtype: int64

This confirms nulls come entirely from VendorID 1 (not missing at random).

In [8]:
# cleaning the data into taxi dataframe
taxi = taxi_raw.copy()
n_before = len(taxi)

# filter to Dec 1, 2024 – Feb 28, 2025 only (exclude out of intended sample dates)
taxi = taxi[
    (taxi['tpep_pickup_datetime'] >= '2024-12-01') &
    (taxi['tpep_pickup_datetime'] < '2025-03-01')
]
print(f"After date filter: {len(taxi):,} rows (removed {n_before - len(taxi):,})")

# drop rows with unknown pickup zones (264, 265)
n = len(taxi)
taxi = taxi[~taxi['PULocationID'].isin([264, 265])]
print(f"After removing unknown zones: {len(taxi):,} rows (removed {n - len(taxi):,})")

# removing errnoeus trips with zero or negative fare
n = len(taxi)
taxi = taxi[taxi['fare_amount'] > 0]
print(f"After removing non-positive fares: {len(taxi):,} rows (removed {n - len(taxi):,})")

# remove extreme fare outliers (> $500) - could be errors, sounds sketchy
n = len(taxi)
taxi = taxi[taxi['fare_amount'] <= 500]
print(f"After removing fare outliers (>$500): {len(taxi):,} rows (removed {n - len(taxi):,})")

# remove cancelled/zero-distance trips
n = len(taxi)
taxi = taxi[taxi['trip_distance'] > 0]
print(f"After removing dist=0 trips: {len(taxi):,} rows (removed {n - len(taxi):,})")

# replace null passenger_count with 1 (most common value) - just to have data clean.
# we are not using passenger_count for taxi demand analysis yet, so its okay to fill it so the data is clean
print(f"\nNull passenger_count before fill: {taxi['passenger_count'].isnull().sum():,}")
taxi['passenger_count'] = taxi['passenger_count'].fillna(1.0)

# get temporal features (change names to something more readable)
taxi['date'] = taxi['tpep_pickup_datetime'].dt.date.astype(str)
taxi['hour'] = taxi['tpep_pickup_datetime'].dt.hour
taxi['day_of_week'] = taxi['tpep_pickup_datetime'].dt.day_name()

# keep only columns we might be interested in
keep_cols = [
    'tpep_pickup_datetime', 'tpep_dropoff_datetime',
    'passenger_count', 'trip_distance', 'PULocationID', 'DOLocationID',
    'fare_amount', 'total_amount', 'date', 'hour', 'day_of_week'
]
taxi = taxi[keep_cols]

print(f"Final taxi shape: {taxi.shape}")
print(f"\nDate range: {taxi['date'].min()} to {taxi['date'].max()}")
print(f"\nRemaining nulls:\n{taxi.isnull().sum()}")

After date filter: 10,721,108 rows (removed 32)
After removing unknown zones: 10,691,219 rows (removed 29,889)
After removing non-positive fares: 10,281,792 rows (removed 409,427)
After removing fare outliers (>$500): 10,281,660 rows (removed 132)
After removing dist=0 trips: 10,057,973 rows (removed 223,687)

Null passenger_count before fill: 1,330,827
Final taxi shape: (10057973, 11)

Date range: 2024-12-01 to 2025-02-28

Remaining nulls:
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
PULocationID             0
DOLocationID             0
fare_amount              0
total_amount             0
date                     0
hour                     0
day_of_week              0
dtype: int64

In [9]:
# summary statistics for our cleaned data
print('Summary statistics for cleaned taxi data:\n')
print(taxi[['passenger_count', 'trip_distance', 'fare_amount', 'total_amount']].describe().round(2))

trips_per_day = taxi.groupby('date').size()
print(f'\nTrips per day: mean={trips_per_day.mean()}, min={trips_per_day.min()}, max={trips_per_day.max()}')

Summary statistics for cleaned taxi data:

       passenger_count  trip_distance  fare_amount  total_amount
count      10057973.00    10057973.00  10057973.00   10057973.00
mean              1.27           5.49        18.81         27.62
std               0.72         503.86        16.58         20.88
min               0.00           0.01         0.01          0.00
25%               1.00           1.01         9.30         16.02
50%               1.00           1.71        13.50         21.00
75%               1.00           3.22        21.20         29.75
max               9.00      328827.63       500.00        615.31

Trips per day: mean=111755.25555555556, min=52112, max=153849

### Dataset 2: NOAA Daily Weather — Central Park (Dec 2024–Feb 2025)

Daily weather summaries from NOAA station USW00094728 (Central Park, Manhattan). This is the standard reference station for NYC weather, recording continuously since 1869.

- **temp_max_f / temp_min_f** — Daily high and low temperatures in degrees Fahrenheit. For Dec 2024–Feb 2025, highs range from the low 40s (late November) to the mid-80s (early September).
- **precipitation_in** — Total liquid precipitation (rain + melted snow) in inches per 24-hour period. Values of 0.001 represent "trace" amounts (originally "T" in the source data).
- **snowfall_in** — New snowfall in inches. Winter months include multiple snow events.
- **snow_on_ground_in** — Snow depth on the ground. Non-zero after snowfall events.

**Concerns:** Central Park is a single station for an entire metro area. Conditions in the outer boroughs or near airports may differ, especially for localized precipitation.

In [10]:
# get the weather data
weather = pd.read_csv('data/00-raw/weather.csv')

print(f"Weather shape: {weather.shape}")
print(f"Date range: {weather['date'].iloc[0]} to {weather['date'].iloc[-1]}")
print(f"\nData types:\n{weather.dtypes}")
print(f"\nNull counts:\n{weather.isnull().sum()}")
print(f"\nDescriptive statistics:")
weather.describe()

Weather shape: (90, 6)
Date range: 2024-12-01 to 2025-02-28

Data types:
date                  object
temp_max_f           float64
temp_min_f           float64
precipitation_in     float64
snowfall_in          float64
snow_on_ground_in    float64
dtype: object

Null counts:
date                 0
temp_max_f           0
temp_min_f           0
precipitation_in     0
snowfall_in          0
snow_on_ground_in    0
dtype: int64

Descriptive statistics:

,temp_max_f,temp_min_f,precipitation_in,snowfall_in,snow_on_ground_in
count,90.000000,90.000000,90.000000,90.000000,90.000000
mean,40.311111,29.311111,0.086067,0.143411,0.362289
std,9.202643,8.603167,0.187261,0.453191,0.702221
min,19.000000,10.000000,0.000000,0.000000,0.000000
25%,34.000000,24.000000,0.000000,0.000000,0.000000
50%,39.000000,29.000000,0.000000,0.000000,0.000000
75%,46.750000,33.000000,0.087500,0.000000,0.001000
max,60.000000,50.000000,0.910000,3.000000,3.100000

In [11]:
# cleaning it
# filling any nulls in snow_on_ground_in with 0
weather['snow_on_ground_in'] = weather['snow_on_ground_in'].fillna(0.0)

# The code below on this cell was partially generated by Claude Opus from the prompt 
# "assume we have weather dataframe with col 'date_parsed' that is pd.datetime
# write code that checks how many missing days there are. We expect to have one
# day for each day in the range 2024-12-01 to 2025-02-28."

# check that there are no gaps on days
weather['date_parsed'] = pd.to_datetime(weather['date'])
expected_days = pd.date_range('2024-12-01', '2025-02-28', freq='D')
missing_days = set(expected_days) - set(weather['date_parsed'])
print(f'Missing days in weather data: {len(missing_days)} (expected 0)')
print(f'Remaining nulls: {weather.isnull().sum().sum()}')

weather = weather.drop(columns=['date_parsed'])
print(f'\nCleaned weather shape: {weather.shape}')

Missing days in weather data: 0 (expected 0)
Remaining nulls: 0

Cleaned weather shape: (90, 6)

### Dataset 3: Taxi Zone Lookup + Merging All Datasets

The zone lookup maps the integer `LocationID` in the trip data to borough and zone names. We join it to the taxi data on `PULocationID` to add `Borough`, `Zone`, and `service_zone`. Then we join weather data on `date` so every trip is enriched with that day's weather.

In [12]:
# get zone data
zones = pd.read_csv('data/00-raw/taxi_zone_lookup.csv')
print(f"Zone lookup shape: {zones.shape}")
print(f"Boroughs: {zones['Borough'].unique()}")
print(f"\nSample:")
zones.head()

Zone lookup shape: (265, 4)
Boroughs: ['EWR' 'Queens' 'Bronx' 'Manhattan' 'Staten Island' 'Brooklyn' 'Unknown'
 nan]

Sample:

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [ ]:
# Merge taxi + zone + weather
# join taxi with zone lookup based on PULocationID
merged = taxi.merge(
    zones, left_on='PULocationID', right_on='LocationID', how='left'
).drop(columns=['LocationID'])

print(f"After zone join: {merged.shape}")
print(f"Null Borough (unmatched zones): {merged['Borough'].isnull().sum()}")

# join with weather on date
merged = merged.merge(weather, on='date', how='left')
print(f"After weather join: {merged.shape}")

# final checks and sanity prints
print(f"\nFinal merged dataset: {merged.shape[0]:,} rows x {merged.shape[1]} columns")
print(f"\nColumn list: {list(merged.columns)}")
print(f"\nRemaining nulls:\n{merged.isnull().sum()}")
print(f"\nSample data:")
merged.head()

After zone join: (10057973, 14)
Null Borough (unmatched zones): 0

In [ ]:
# save changes to processed dir
merged.to_parquet('data/02-processed/taxi_weather_merged.parquet', index=False)
print(f"Saved merged dataset to data/02-processed/taxi_weather_merged.parquet")

# save cleaned individual data to their interim dirs
taxi.to_parquet('data/01-interim/taxi_cleaned.parquet', index=False)
weather.to_csv('data/01-interim/weather_cleaned.csv', index=False)
print(f"Saved cleaned taxi to data/01-interim/taxi_cleaned.parquet")
print(f"Saved cleaned weathe to data/01-interim/weather_cleaned.csv")

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Temporal Features

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_parquet("data/02-processed/taxi_weather_merged.parquet")

print(df.shape)
df.head()

In [ ]:
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

df["hour"] = df["tpep_pickup_datetime"].dt.hour
df["day_of_week"] = df["tpep_pickup_datetime"].dt.day_name()
df["date"] = df["tpep_pickup_datetime"].dt.date

day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
df["day_of_week"] = pd.Categorical(df["day_of_week"], categories=day_order, ordered=True)

In [ ]:
hourly_demand = df.groupby("hour").size()

plt.figure(figsize=(10,5))
sns.lineplot(x=hourly_demand.index, y=hourly_demand.values)
plt.title("Taxi Demand by Hour of Day")
plt.xlabel("Hour")
plt.ylabel("Number of Trips")
plt.show()

In [ ]:
dow_demand = df.groupby("day_of_week").size()

plt.figure(figsize=(10,5))
sns.barplot(x=dow_demand.index, y=dow_demand.values)
plt.title("Taxi Demand by Day of Week")
plt.xlabel("Day")
plt.ylabel("Number of Trips")
plt.xticks(rotation=45)
plt.show()

In [ ]:
daily_demand = df.groupby("date").size()

plt.figure(figsize=(12,5))
sns.lineplot(x=daily_demand.index, y=daily_demand.values)
plt.title("Daily Taxi Demand Over Time")
plt.xlabel("Date")
plt.ylabel("Trips")
plt.xticks(rotation=45)
plt.show()

In [ ]:
pivot = df.pivot_table(index="hour",columns="day_of_week",values="trip_distance",aggfunc="count")

plt.figure(figsize=(10,6))
sns.heatmap(pivot, cmap="YlOrRd")
plt.title("Taxi Demand Heatmap (Hour vs Day)")
plt.xlabel("Day of Week")
plt.ylabel("Hour")
plt.show()

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent? 
 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those? 
 - [ ] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
 - [ ] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

### B. Data Storage
 - [ ] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [ ] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)? 
 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)? 
 - [ ] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
 - [ ] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
 - [ ] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory? X 
 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)? X 
 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [ ] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [ ] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

Notes on ethical considerations:

The TLC trip data is collected without explicit rider consent, but does not have identifiable information about riders (A.1). Also it only covers TLC-regulated vehicles, leaving out public transit, biking, and personal cars (A.2). There are missing perspectives and dataset bias because we do not know anything about the riders (including reason for getting a taxi), and Manhattan is likely to skew the results due to being a densely populated area (C.1, C.2). Location features like pick-up and drop-off zones can also proxy for race and income due to NYC's geographical segregation (D.1, D.2).

As for location, the TLC's dataset divides NYC into 263 zones, which protects passenger privacy by avoiding exact GPS coordinates.

## Team Expectations

Read over the [COGS108 Team Policies](https://github.com/COGS108/Projects/blob/master/COGS108_TeamPolicies.md) individually. Then, include your group's expectations of one another for successful completion of your COGS108 project below. Discuss and agree on what all of your expectations are. Discuss how your team will communicate throughout the quarter and consider how you will communicate respectfully should conflicts arise. By including each member's name above and by adding their name to the submission, you are indicating that you have read the COGS108 Team Policies, accept your team's expectations below, and have every intention to fulfill them. These expectations are for your team's use and benefit — they won't be graded for their details.

* Communicate using our Discord group chat.
* Reasonable to wait around 3-7 hours for a message to be replied to.
* We will meet once a week, on either Tuesday or Thursday, in person.
* Blunt but polite tone encouraged.
* Majority vote is how we will deal with things.
* Everyone will do a little bit of everything with tasks
* Keep track of everything using Google Sheets
* If someone is struggling, they should notify the group at least 72 hours after they have been struggling to find data information.

## Project Timeline Proposal


| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|-------------|--------------|--------------------------|--------------------|
| 2/4 | 8 pm | Reading and Discussing COGS 108 expectations. | Brainstorm topics for final project and decide on idea; discuss hypothesis; begin background research; submit project proposal. <br>Content covered in meeting:<br>- Decided on final project idea and research question: Out of specific features between temporal, spatial, and weather, which feature or combination of features has the most important effect on taxi-demands in New York City?<br>- Began brainstorming hypothesis.<br>- Background research was mostly completed during the meeting with data sets found, pending selection of ideal data sets. |
| 2/10 | 8 pm | Background research on topic; search for data sets. | Discuss ideal data sets; discuss wrangling and possible analytical approaches; assign roles for each group member to lead a specific part. <br>Content covered in meeting:<br>- Refined hypothesis to match and relate to our data sets.<br>- Discussed and found ideal data sets to use for the final project.<br>- Began wrangling data for ideal data sets. |
| 2/19 | 8 pm | Import and Wrangle Data; EDA | Review/Edit wrangling and EDA; discuss analysis plan. Decide on five pairs of features (one for each member) to dig deeper, including potential confounding variables and correlations with taxi demand, based on the correlation matrix of all variables. |
| 2/26 | 8 pm | Finalize wrangling/EDA; Begin Analysis | Discuss/edit analysis with focus on preliminary visualizations and model development/comparison based on feature selection from the previous meeting; complete project check-in. |
| 3/12 | 8 pm | Complete analysis; Draft results/conclusion/discussion | Discuss/edit full project with focus on finalizing plots, interpreting results, comparing model outcomes, and refining conclusions and final submission. Test selected features. |
| 3/20 | Before 11:59 pm | NA | Turn in Final Project and Group Project Surveys |